### ISSUE TITLE
Mac OS X is not supporting static binaries - it doesn't build on Mac

### ISSUE THREAD

**Issue by bartsmykla** [GoogleCloudPlatform/k8s-container-image-promoter#2]
It seems like Mac OS X doesn't support static binaries: https://developer.apple.com/library/content/qa/qa1118/_index.html
so Bazel is failing when trying to build cip on MacOS

I think that we could implement simple fix for that, like kubectl: https://github.com/kubernetes/kubernetes/commit/46e894bfd3bd23cb67a4324f86fc7bd91a7423ce#diff-f5ebbdbdf8b4060ed24bc6ac0dcbad75

Let me create a simple PR for that, and if you won't agree with me, we can just close it. :-)

**Comment by listx** [comment]
Sounds good to me. Please feel free to add a PR for that. I do have some bazel changes in the pipeline --- let me merge that in first.
